### ISSUE TITLE
Editions Page

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#105]
1. All tiles should be of equal size
2. Title of the edition should include name of manuscript (abbreviation?)
3. "Published At: N/A" - should be "Published:" - if there is no publication date for original editions, perhaps add date of scrollery release
4. Information should be added to the edition tiles (number of fragments or images, for example), or other information that can be helpful to the user. Can be taken from the manifests.

**Comment by Bronson-Brown-deVost** [comment]
1. Agreed
2. This sounds good too (though in the case of radical rethinking of joins and reconstructions, the manuscript name may become rather meaningless).
3. Agreed, I will alter the database so that no edition lacks a publication date.
4. Let's discuss what might be needed.  It may not be trivial to get this data, so we might need to load it on demand (as the cards scroll into view).

**Comment by tsviar** [comment]
Fixed in branch "fix/GIT-issues-rest
![image](https://user-images.githubusercontent.com/16132723/120235282-5b57db00-c262-11eb-9d99-ea961bcdd6ec.png)
![image](https://user-images.githubusercontent.com/16132723/120235296-627ee900-c262-11eb-8a59-60f87cf424b0.png)
![image](https://user-images.githubusercontent.com/16132723/120235313-67439d00-c262-11eb-908d-d0fa8880a736.png)
![image](https://user-images.githubusercontent.com/16132723/120235329-6f9bd800-c262-11eb-9092-66e3e4aff153.png)
![image](https://user-images.githubusercontent.com/16132723/120235344-77f41300-c262-11eb-9bcb-36bb275cdc76.png)
