### ISSUE TITLE
Tiles with no pictures

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#112]
The tiles without photos appear with a scroll icon. however, when clicked on, nothing appears. there is no reason for them to appear if no photos/text are available.  If it is important to display for catalogue reasons, there should be a notice of "No images available"

**Comment by Bronson-Brown-deVost** [comment]
@OritandJoe can you provide an example?

**Comment by OritandJoe** [comment]
Like this:
https://www.qumranica.org/Scrollery/editions/706/artefacts 
![tempsnip3](https://user-images.githubusercontent.com/83159010/117286929-75281d00-ae72-11eb-8cfe-9f5d15595c90.png)
And allow for adding text for a scholar that creates a personal copy of the manuscript

**Comment by Bronson-Brown-deVost** [comment]
OK, that makes sense.  These exist because there is text transcription available for the scroll.

We do have the capability to show just text, and to let people work with that.  @zmbq @tsviar, we should probably list the available text fragments in this panel (so would would be able to see a list of: 'Artefacts', 'Imaged Objects', and 'Text Fragments').  You get that list with /v1/editions/{editionId}/text-fragments (I won't have time to add text snippets by launch, though that could be something nice to add later).  You already have the router set up to support this (you currently access it from the search interface), for example http://localhost:8080/editions/900/text-fragments/10181.

Let's all decide after some more debugging is done whether we want to add this functionality (a third list for text fragments in the manuscript info pane), or we will hide these at launch date (I would add a flag in the API endpoint to enable/disable retrieval of listings for scrolls without any images).
