### ISSUE TITLE
Sort

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#113]
1. Sort on Personal Editions page: Sort by Last edited does not work
2. Sort on Public editions should be "Sort by Publication Date" and not "Sort by Last Edit"
3. Sort by Name - Numbers do not sort correctly (1Q appears after 11Q and 10 Q, etc.)

**Comment by Bronson-Brown-deVost** [comment]
1. See my comment about sorting on #114 
2. Agreed
3. Can we get a "natural sort" working here?  I also find it super annoying that when searching for "1q7" the edition of "1Q7" is the last entry (after 11Q7 and 1Q70–1Q72).  Why don't computers think like me!

**Comment by tsviar** [comment]
Sort fixed in branch fix/GIT-issues-rest.
Sort has now "Date" and "Name" as sort options, that way it works for both Personal and Public editions.
Bear in mind, that the sort will show 1Q7 on the first line only when sort name option is selected,
and also sort by date is the default option.

![image](https://user-images.githubusercontent.com/16132723/120369815-7edf5c00-c31c-11eb-9d74-dbdc02a3c227.png)
![image](https://user-images.githubusercontent.com/16132723/120369866-90c0ff00-c31c-11eb-8586-81f3f2efa053.png)
![image](https://user-images.githubusercontent.com/16132723/120369918-a20a0b80-c31c-11eb-8f6f-e6c1e5ab9d20.png)
![image](https://user-images.githubusercontent.com/16132723/120369991-b817cc00-c31c-11eb-859f-a9eb7ffda6cb.png)
![image](https://user-images.githubusercontent.com/16132723/120370081-ce258c80-c31c-11eb-9433-2fc352bfaa7f.png)
![image](https://user-images.githubusercontent.com/16132723/120370148-e4334d00-c31c-11eb-982f-1fdea9c5fd36.png)
