### ISSUE TITLE
Add Create a Copy option in all windows

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#117]
When entering view mode of public editions, there should be an option of "Create a Copy" on toolbar

**Comment by Bronson-Brown-deVost** [comment]
Agreed, this would make it very easy to start your own edition of the scroll at any point while investigating a public edition. In the top bar where it says "published", we should add a "copy" button. @OritandJoe is that what you had in mind, and how should it be labeled exactly (remember that space is limited)?

**Comment by OritandJoe** [comment]
It should be clear to the user that he is in a screen that is view only and if he wants to edit, he needs to create a copy.
Maybe something like these? 
![tempsnip](https://user-images.githubusercontent.com/83159010/117286112-73aa2500-ae71-11eb-9caa-9237719c0406.png)
![tempsnip2](https://user-images.githubusercontent.com/83159010/117286116-74db5200-ae71-11eb-88a8-0fb8bc49b045.png)

**Comment by tsviar** [comment]
Fixed in branch fix/GIT-issues-rest
Copy link was added to all View except Manuscript view, due to lack of space.
![image](https://user-images.githubusercontent.com/16132723/120684920-f1c90e00-c4a7-11eb-927c-2eccffcb1c71.png)
![image](https://user-images.githubusercontent.com/16132723/120684951-f988b280-c4a7-11eb-86dc-270f9cd8241e.png)
![image](https://user-images.githubusercontent.com/16132723/120685000-073e3800-c4a8-11eb-9e55-4aaee7537502.png)
![image](https://user-images.githubusercontent.com/16132723/120685022-0d341900-c4a8-11eb-8f5e-23784999962e.png)

![image](https://user-images.githubusercontent.com/16132723/120685029-11603680-c4a8-11eb-87ee-188ce0564275.png)
![image](https://user-images.githubusercontent.com/16132723/120685054-1a510800-c4a8-11eb-975f-12ad09faabdc.png)
