### ISSUE TITLE
Artefact Mode Doesn't refresh

### ISSUE THREAD

**Issue by Bronson-Brown-deVost** [Scripta-Qumranica-Electronica/ScrollEditor#154]
@zmbq If you select an artefact and view it in the artefact mode, you will get a browser hang when you click back and select the same artefact.  This also happens if you click on the edition name instead of using the back button.  Clicking refresh on the browser when it is hung will successfully load the artefact again.

**Comment by zmbq** [comment]
@Bronson-Brown-deVost , nice catch! There was a flaw in the cache mechanism of our internal state. We had all those 'prepare' functions that fetch the necessary data for the Vue components. These are cached, so that if you prepare the same edition or same artefact twice, the second time does nothing.

Problem is, preparing both fetches the artefact data *and* sets the current artefact to the fetched artefact. If the function isn't called, the current artefact isn't set.

I added a "post" function for each prepare function (well, only for editions and artefacts, no need for others just yet), which is called even if the main prepare function isn't called.
