### ISSUE TITLE
error when showing QWB variants

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#166]
![image](https://user-images.githubusercontent.com/83159010/124714757-d5871980-df0a-11eb-8dc5-45f20b3828de.png)

**Comment by zmbq** [comment]
I think the handling of variants should be redone, instead of one modal per sign we should have one system-wide modal that gets the sign ID and populates the modal.

However, there seems to be several kinds of such modals. I think we should discuss the requested functionality so I can figure out how to do it.

@Bronson-Brown-deVost
